<a href="https://colab.research.google.com/github/erwanmaulana/Tugas-ML/blob/main/Minggu9_3_3_LinearRegresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!pip install d2l==0.17.0

In [15]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [16]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [17]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.1274269 , -0.32724252],
        [-1.0004901 ,  2.10285   ],
        [ 0.17301115,  1.1531442 ],
        [ 1.1781105 , -2.154124  ],
        [-2.0478525 ,  0.5903773 ],
        [-0.4681117 , -1.4392554 ],
        [ 0.554799  ,  1.2874813 ],
        [-1.1776459 ,  1.279855  ],
        [-0.26932564, -0.23588923],
        [-1.2727264 , -0.67403823]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 7.577219 ],
        [-4.950071 ],
        [ 0.6038043],
        [13.888198 ],
        [-1.909914 ],
        [ 8.146638 ],
        [ 0.9187798],
        [-2.4861822],
        [ 4.4612355],
        [ 3.9398744]], dtype=float32)>)

In [18]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [19]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [20]:
loss = tf.keras.losses.MeanSquaredError()

In [21]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [22]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000255
epoch 2, loss 0.000106
epoch 3, loss 0.000106


In [23]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-0.000144    0.00073743], shape=(2,), dtype=float32)
error in estimating b [-0.00078678]
